# Generated by Django 5.1.2 on 2024-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizstatus',
            name='created_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userquizstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
